theme: jekyll-theme-leap-day
title: Ayush Baid
description: GaTech | IIT Bombay
show_downloads: false
plugins:
  - jekyll-seo-tag
github:
  is_project_page: false
  
webmaster_verifications:
  google: -gtpTDwhx8zNThdl3XEQuA8VBSmjqWVuGYrE0Um841A
